export const reviews = [
    {
        id: 1,
        img: 'Images/images.png',
        description: "Absolutely love it! The attention to detail is amazing, and it adds a touch of charm wherever I place it.",
        name: "Sarojini",
        position: 'Thanjavur'
    },
    {
        id: 2,
        img: 'Images/images.png',
        description: "Great product, it to anyone looking for something unique. It's beautifully crafted and made a perfect gift.",
        name: "Hema",
        position: 'Thanjavur'
    },
    {
        id: 3,
        img: 'Images/images.png',
        description: "Very happy with my purchase! It exceeded my expectations in terms of quality and design.",
        name: "Rajeshwari",
        position: 'Thanjavur'
    },
    {
        id: 4,
        img: 'Images/images.png',
        description: "Perfect addition to my home decor, it fits perfectly with my style and brings a cozy feel to the room.",
        name: "Sherin Taj",
        position: 'Thanjavur'
    },
    {
        id: 5,
        img: 'Images/images.png',
        description: "Beautiful craftsmanship! It's clear a lot of care went into making it, and it's now a cherished piece in my collection.",
        name: "Sreema",
        position: 'Thanjavur'
    },
    {
        id: 6,
        img: 'Images/images.png',
        description: "Such a thoughtful gift! It brought a smile to my face and was wonderfully received by the recipient.",
        name: "Raseena Farveen",
        position: 'Thanjavur'
    },
    {
        id: 7,
        img: 'Images/images.png',
        description: "Exactly what I was looking for. It's even better in person and has become a focal point in my space.",
        name: "Jagasree",
        position: 'Thanjavur'
    },
    {
        id: 8,
        img: 'Images/images.png',
        description: "Impressed with the quality, definitely worth it. I appreciate the craftsmanship and attention to detail.",
        name: "Menaga",
        position: 'Thanjavur'
    },
    {
        id: 9,
        img: 'Images/images.png',
        description: "Wonderful experience! The whole process was seamless, from ordering to delivery.It's beautifully crafted and made a perfect gift.",
        name: "Aravindh",
        position: 'Thanjavur'
    },
    {
        id: 10,
        img: 'Images/images.png',
        description: "Couldn't be happier with my purchase. It's a great addition to my collection and has exceeded my expectations.",
        name: "Shiva",
        position: 'Thanjavur'
    },
];


export const products = [
    {
        id: 1,
        name: 'Cashew',
        rating: 5,
        price: '₹365.00',
        image: 'Images/ProductsImages/cashew-2.png',
        unitsSold: '50',
    },
    {
        id: 2,
        name: 'Cashew Splits',
        rating: 4,
        price: '₹425.00',
        image: 'Images/ProductsImages/pepper cashew..png',
        unitsSold: 45,
    },
    {
        id: 3,
        name: 'Roasted Cashew',
        rating: 4,
        price: '₹425.00',
        image: 'Images/ProductsImages/Purely Delight (1).png',
        unitsSold: 43,
    },
    {
        id: 4,
        name: 'Roasted Cashew',
        rating: 3,
        price: '₹800',
        image: 'Images/ProductsImages/Purely Delight (2).png',
        unitsSold: 25,
    },
    {
        id: 5,
        name: 'Roasted Cashew',
        rating: 4,
        price: '₹425.00',
        image: 'Images/ProductsImages/Purely Delight (3).png',
        unitsSold: 43,
    },
    {
        id: 6,

        name: 'Roasted Cashew',
        rating: 4,
        price: '₹425.00',
        image: 'Images/ProductsImages/Purely Delight (4).png',
        unitsSold: 43,
    },
    {
        id: 7,

        name: 'Roasted Cashew',
        rating: 4,
        price: '₹425.00',
        image: 'Images/ProductsImages/Purely Delight (5).png',
        unitsSold: 43,
    },
    {
        id: 8,
        name: 'Roasted Cashew',
        rating: 4,
        price: '₹425.00',
        image: 'Images/ProductsImages/Purely Delight (6).png',
        unitsSold: 43,
    },
    {
        id: 9,
        name: 'Roasted Cashew',
        rating: 4,
        price: '₹425.00',
        image: 'Images/ProductsImages/Purely Delight (7).png',
        unitsSold: 43,
    },
    {
        id: 10,
        name: 'Roasted Cashew',
        rating: 4,
        price: '₹425.00',
        image: 'Images/ProductsImages/sunflower seeds.png',
        unitsSold: 43,
    },
    {
        id: 11,
        name: 'Roasted Cashew',
        rating: 4,
        price: '₹425.00',
        image: 'Images/ProductsImages/wallnut.png',
        unitsSold: 43,
    },
    {
        id: 12,
        name: 'Roasted Cashew',
        rating: 4,
        price: '₹425.00',
        image: 'Images/ProductsImages/watermelon seeds.png',
        unitsSold: 43,
    },
];


export const dryfruits = [
    {
        id: 1,
        name: 'Apricot',
        rating: 5,
        price: '₹125.00',
        image: 'Images/ProductsImages/dryFruits/Apricot.png',
        unitsSold: '50',
    },
    {
        id: 2,
        name: 'Baby Orange',
        rating: 4,
        price: '₹60.00',
        image: 'Images/ProductsImages/dryFruits/baby orange.png',
        unitsSold: 45,
    },
    {
        id: 3,
        name: 'Black Current',
        rating: 4,
        price: '₹70.00',
        image: 'Images/ProductsImages/dryFruits/Blackcurrent.png',
        unitsSold: 43,
    },
    {
        id: 4,
        name: 'Blue Berry',
        rating: 3,
        price: '₹190.00',
        image: 'Images/ProductsImages/dryFruits/blueberry.png',
        unitsSold: 25,
    },
    {
        id: 5,
        name: 'Cherry',
        rating: 4,
        price: '₹85.00',
        image: 'Images/ProductsImages/dryFruits/Cherry.png',
        unitsSold: 43,
    },
    {
        id: 6,
        name: 'Dry Papaya',
        rating: 4,
        price: '₹75.00',
        image: 'Images/ProductsImages/dryFruits/Drypapaya.png',
        unitsSold: 43,
    },
    {
        id: 7,
        name: 'Dry Amla ',
        rating: 4,
        price: '₹45.00',
        image: 'Images/ProductsImages/dryFruits/dry amla.png',
        unitsSold: 43,
    },
    {
        id: 8,

        name: 'Ginger Cubes',
        rating: 4,
        price: '₹68.00',
        image: 'Images/ProductsImages/dryFruits/ginger cubes.png',
        unitsSold: 43,
    },
    {
        id: 9,

        name: 'Ginger Slices',
        rating: 4,
        price: '₹50.00',
        image: 'Images/ProductsImages/dryFruits/ginger slice.png',
        unitsSold: 43,
    },
    {
        id: 10,
        name: 'Honey Amla',
        rating: 4,
        price: '₹60.00',
        image: 'Images/ProductsImages/dryFruits/honey amla.png',
        unitsSold: 43,
    },
    {
        id: 11,
        name: 'Mango Slice',
        rating: 4,
        price: '₹78.00',
        image: 'Images/ProductsImages/dryFruits/Mango slice.png',
        unitsSold: 43,
    },
    {
        id: 12,
        name: 'Pineapple Coin',
        rating: 4,
        price: '₹65.00',
        image: 'Images/ProductsImages/dryFruits/pineapple coin.png',
        unitsSold: 43,
    },
    {
        id: 13,
        name: 'Pineapple Ring',
        rating: 4,
        price: '₹72.00',
        image: 'Images/ProductsImages/dryFruits/Pineapple ring.png',
        unitsSold: 43,
    },
    {
        id: 14,
        name: 'Pomelo',
        rating: 4,
        price: '₹65.00',
        image: 'Images/ProductsImages/dryFruits/pomelo.png',
        unitsSold: 43,
    },
    {
        id: 15,
        name: 'Mixed Fruits',
        rating: 4,
        price: '₹80.00',
        image: 'Images/ProductsImages/dryFruits/Mixedfruits.jpg',
        unitsSold: 43,
    },
    {
        id: 16,
        name: 'Raspberry',
        rating: 4,
        price: '₹400.00',
        image: 'Images/ProductsImages/dryFruits/Rashberry.png',
        unitsSold: 43,
    },
    {
        id: 17,
        name: 'Strawberry',
        rating: 4,
        price: '₹138.00',
        image: 'Images/ProductsImages/dryFruits/strawberry.png',
        unitsSold: 43,
    },
    {
        id: 18,
        name: 'Yellow Peach',
        rating: 4,
        price: '₹65.00',
        image: 'Images/ProductsImages/dryFruits/yellow peach.png',
        unitsSold: 43,
    },
    {
        id: 19,
        name: 'Masala Guava',
        rating: 4,
        price: '₹120.00',
        image: 'Images/ProductsImages/dryFruits/Masalaguava.jpg',
        unitsSold: 43,
    },
    {
        id: 20,
        name: 'Kiwi',
        rating: 4,
        price: '₹60.00',
        image: 'Images/ProductsImages/dryFruits/kiwi.jpg',
        unitsSold: 43,
    },
    {
        id: 21,
        name: 'Gojiberry',
        rating: 4,
        price: '₹150.00',
        image: 'Images/ProductsImages/dryFruits/gojiberries.jpg',
        unitsSold: 43,
    },
    {
        id: 22,
        name: 'Prunes',
        rating: 4,
        price: '₹110.00',
        image: 'Images/ProductsImages/dryFruits/prunes.jpg',
        unitsSold: 43,
    },
];



export const nuts = [
    {
        id: 1,
        name: 'Almond',
        rating: 5,
        price: '₹65.00/₹75.00',
        image:'Images/ProductsImages/nuts/Almond.png',
        unitsSold: '50',
    },
    {
        id: 2,
        name: 'Anjeer Figs',
        rating: 5,
        price: '₹90.00/₹140.00',
        image: 'Images/ProductsImages/nuts/Anjeer.png',
        unitsSold: '50',
    },
    {
        id: 3,
        name: 'Brazil Nuts',
        rating: 4,
        price: '₹220.00',
        image: 'Images/ProductsImages/nuts/Brazil nuts.png',
        unitsSold: 45,
    },
    {
        id: 4,
        name: 'Cashew',
        rating: 4,
        price: '₹95.00/₹75.00',
        image: 'Images/ProductsImages/nuts/Cashew.png',
        unitsSold: 43,
    },
    {
        id: 5,
        name: 'Pecan Nuts',
        rating: 3,
        price: '₹240.00',
        image: 'Images/ProductsImages/nuts/Pecan nut.png',
        unitsSold: 25,
    },
    {
        id: 6,
        name: 'Pepper Cashew',
        rating: 4,
        price: '₹95.00',
        image: 'Images/ProductsImages/nuts/pepper cashew.png',
        unitsSold: 43,
    },
    {
        id: 7,
        name: 'Pine Nuts',
        rating: 4,
        price: '₹800.00',
        image: 'Images/ProductsImages/nuts/Pine nuts.png',
        unitsSold: 43,
    },
    {
        id: 8,
        name: 'Pistachios',
        rating: 4,
        price: '₹110.00/₹125.00',
        image: 'Images/ProductsImages/nuts/pista.png',
        unitsSold: 43,
    },
    {
        id: 9,
        name: 'Salted Almond',
        rating: 4,
        price: '₹95.00',
        image: 'Images/ProductsImages/nuts/salted almond.png',
        unitsSold: 43,
    },
    {
        id: 10,

        name: 'Salted Cashew',
        rating: 4,
        price: '₹95.00',
        image: 'Images/ProductsImages/nuts/salted cashew.png',
        unitsSold: 43,
    },
    {
        id: 11,
        name: 'Walnut',
        rating: 4,
        price: '₹130.00/₹160.00',
        image: 'Images/ProductsImages/nuts/wallnut.png',
        unitsSold: 43,
    },
    {
        id: 12,
        name: 'Chilli Cashew',
        rating: 4,
        price: '₹95.00',
        image: 'Images/ProductsImages/nuts/chillicashew.jpg',
        unitsSold: 43,
    },
    {
        id: 13,
        name: 'Periperi Cashew',
        rating: 4,
        price: '₹95.00',
        image: 'Images/ProductsImages/nuts/peripericashew.jpg',
        unitsSold: 43,
    },
    {
        id: 14,
        name: 'Indian Grapes',
        rating: 4,
        price: '₹28.00',
        image: 'Images/ProductsImages/nuts/Indiangrape.jpg',
        unitsSold: 43,
    },
    {
        id: 15,
        name: 'Afghan Grapes',
        rating: 4,
        price: '₹60.00',
        image: 'Images/ProductsImages/nuts/Afghangrape.jpg',
        unitsSold: 43,
    },
    {
        id: 16,
        name: 'Hazle Nut',
        rating: 4,
        price: '₹140.00',
        image: 'Images/ProductsImages/nuts/Hazlenut.jpg',
        unitsSold: 43,
    },
];



export const seeds = [
    {
        id: 1,
        name: 'Blackgrape Seeds',
        rating: 5,
        price: '₹36.00',
        image: 'Images/ProductsImages/seeds/Black grapes  seeds.png',
        unitsSold: '50',
    },
    {
        id: 2,
        name: 'Chia Seeds',
        rating: 4,
        price: '₹55.00',
        image: 'Images/ProductsImages/seeds/chia seeds.png',
        unitsSold: 45,
    },
    {
        id: 3,
        name: 'Flax Seeds',
        rating: 4,
        price: '₹40.00',
        image: 'Images/ProductsImages/seeds/flax seed.png',
        unitsSold: 43,
    },
    {
        id: 4,
        name: 'Karunjeeragam Seeds',
        rating: 3,
        price: '₹50.00',
        image: 'Images/ProductsImages/seeds/Karunjeeragam  seeds.png',
        unitsSold: 25,
    },
    {
        id: 5,
        name: 'Poppy Seeds',
        rating: 4,
        price: '₹50.00',
        image: 'Images/ProductsImages/seeds/Poppy seeds.png',
        unitsSold: 43,
    },
    {
        id: 6,

        name: 'Pumpkin Seeds',
        rating: 4,
        price: '₹60.00',
        image: 'Images/ProductsImages/seeds/pumpkin seeds.png',
        unitsSold: 43,
    },
    {
        id: 7,
        name: 'Sabja Seeds',
        rating: 4,
        price: '₹50.00',
        image: 'Images/ProductsImages/seeds/sabja seeds.png',
        unitsSold: 43,
    },
    {
        id: 8,
        name: 'Sunflower Seeds',
        rating: 4,
        price: '₹45.00',
        image: 'Images/ProductsImages/seeds/sunflower seeds (1).png',
        unitsSold: 43,
    },
    {
        id: 9,
        name: 'Watermelon Seeds',
        rating: 4,
        price: '₹105.00',
        image: 'Images/ProductsImages/seeds/watermelon seeds (1).png',
        unitsSold: 43,
    },
    {
        id: 10,
        name: 'Walnuts',
        rating: 4,
        price: '₹130.00',
        image: 'Images/ProductsImages/nuts/wallnut.png',
        unitsSold: 43,
    },
    {
        id: 11,
        name: 'Vellari Seeds',
        rating: 4,
        price: '₹130.00',
        image: 'Images/ProductsImages/seeds/vellari.jpg',
        unitsSold: 43,
    },


];



export const dates = [
    {
        id: 1,
        name: 'Ajwa Dates',
        rating: 5,
        price: '₹1200.00',
        image: 'Images/ProductsImages/dates/ajwa dates.png',
        unitsSold: '50',
    },
    {
        id: 2,
        name: 'Khimiya Dates',
        rating: 4,
        price: '₹750.00',
        image: 'Images/ProductsImages/dates/khimiya   dates.png',
        unitsSold: 45,
    },
    {
        id: 3,
        name: 'Medjoul Dates',
        rating: 4,
        price: '₹1500.00',
        image: 'Images/ProductsImages/dates/medjoul  dates.png',
        unitsSold: 43,
    },
    {
        id: 4,
        name: 'Kimia Dates',
        rating: 4,
        price: '₹260.00',
        image: 'Images/ProductsImages/dates/kimia.jpg',
        unitsSold: 43,
    },
    {
        id: 5,
        name: 'Mabroom Dates',
        rating: 4,
        price: '₹1250.00',
        image: 'Images/ProductsImages/dates/Mabroom.jpg',
        unitsSold: 43,
    },
    {
        id: 6,
        name: 'Mashrook Dates',
        rating: 4,
        price: '₹850.00',
        image: 'Images/ProductsImages/dates/Mashrook.jpg',
        unitsSold: 43,
    },
    {
        id: 7,
        name: 'Barrari Dates',
        rating: 4,
        price: '₹560.00',
        image: 'Images/ProductsImages/dates/Barrari.jpg',
        unitsSold: 43,
    },
    {
        id: 8,
        name: 'Muscat Dates',
        rating: 4,
        price: '₹250.00',
        image: 'Images/ProductsImages/dates/Muscat.jpg',
        unitsSold: 43,
    },
    {
        id: 9,
        name: 'Joiner-65',
        rating: 4,
        price: '₹250.00',
        image: 'Images/ProductsImages/juice/joiner.jpg',
        unitsSold: 43,
    },
    {
        id: 10,
        name: 'Joiner-65',
        rating: 4,
        price: '₹250.00',
        image: 'Images/ProductsImages/juice/joiner1.jpg',
        unitsSold: 43,
    },
    
];




// export const footerProducts = [
//     {
//         id: 1,
//
//         name: 'Cashew',
//         rating: 5,
//         price: '₹365.00',
//         image: 'Images/ProductsImages/cashew-2.png',
//         unitsSold: '50',
//     },
//     {
//         id: 2,
//
//         name: 'Cashew Splits',
//         rating: 4,
//         price: '₹425.00',
//         image: 'Images/ProductsImages/pepper cashew..png',
//         unitsSold: 45,
//     },
//     {
//         id: 3,
//
//         name: 'Roasted Cashew',
//         rating: 4,
//         price: '₹425.00',
//         image: 'Images/ProductsImages/Purely Delight (1).png',
//         unitsSold: 43,
//     },
//     {
//         id: 4,
//
//         name: 'Roasted Cashew',
//         rating: 3,
//         price: '₹800',
//         image: 'Images/ProductsImages/Purely Delight (2).png',
//         unitsSold: 25,
//     },
//     {
//         id: 5,
//
//         name: 'Roasted Cashew',
//         rating: 4,
//         price: '₹425.00',
//         image: 'Images/ProductsImages/Purely Delight (3).png',
//         unitsSold: 43,
//     },
//     {
//         id: 8,
//
//         name: 'Roasted Cashew',
//         rating: 4,
//         price: '₹425.00',
//         image: 'Images/ProductsImages/Purely Delight (6).png',
//         unitsSold: 43,
//     },
//     {
//         id: 9,
//
//         name: 'Roasted Cashew',
//         rating: 4,
//         price: '₹425.00',
//         image: 'Images/ProductsImages/Purely Delight (7).png',
//         unitsSold: 43,
//     },
//     {
//         id: 10,
//
//         name: 'Roasted Cashew',
//         rating: 4,
//         price: '₹425.00',
//         image: 'Images/ProductsImages/sunflower seeds.png',
//         unitsSold: 43,
//     },
//     {
//         id: 11,
//
//         name: 'Roasted Cashew',
//         rating: 4,
//         price: '₹425.00',
//         image: 'Images/ProductsImages/wallnut.png',
//         unitsSold: 43,
//     },
//     {
//         id: 12,
//
//         name: 'Roasted Cashew',
//         rating: 4,
//         price: '₹425.00',
//         image: 'Images/ProductsImages/watermelon seeds.png',
//         unitsSold: 43,
//     },
// ];