export const reviews = [
    {
        id: 1,
        img: 'Images/images.png',
        description: "Absolutely love it! The attention to detail is amazing, and it adds a touch of charm wherever I place it.",
        name: "Sarojini",
    },
    {
        id: 2,
        img: 'Images/images.png',
        description: "Great product, it to anyone looking for something unique. It's beautifully crafted and made a perfect gift.",
        name: "Hema",
    },
    {
        id: 3,
        img: 'Images/images.png',
        description: "Very happy with my purchase! It exceeded my expectations in terms of quality and design.",
        name: "Rajeshwari",
    },
    {
        id: 4,
        img: 'Images/images.png',
        description: "Perfect addition to my home decor, it fits perfectly with my style and brings a cozy feel to the room.",
        name: "Sherin Taj",
    },
    {
        id: 5,
        img: 'Images/images.png',
        description: "Beautiful craftsmanship! It's clear a lot of care went into making it, and it's now a cherished piece in my collection.",
        name: "Sreema",
    },
    {
        id: 6,
        img: 'Images/images.png',
        description: "Such a thoughtful gift! It brought a smile to my face and was wonderfully received by the recipient.",
        name: "Raseena Farveen",
    },
    {
        id: 7,
        img: 'Images/images.png',
        description: "Exactly what I was looking for. It's even better in person and has become a focal point in my space.",
        name: "Jagasree",
    },
    {
        id: 8,
        img: 'Images/images.png',
        description: "Impressed with the quality, definitely worth it. I appreciate the craftsmanship and attention to detail.",
        name: "Menaga",
    },
    {
        id: 9,
        img: 'Images/images.png',
        description: "Wonderful experience! The whole process was seamless, from ordering to delivery.It's beautifully crafted and made a perfect gift.",
        name: "Aravindh",
    },
    {
        id: 10,
        img: 'Images/images.png',
        description: "Couldn't be happier with my purchase. It's a great addition to my collection and has exceeded my expectations.",
        name: "Shiva",
    },
];


export const products = [
    {
        id: 1,
        category: 'Bangles',
        name: 'Cashew',
        rating: 5,
        price: '₹365.00',
        image: 'Images/ProductsImages/cashew-2.png',
        unitsSold: '50',
    },
    {
        id: 2,
        category: 'Bangles',
        name: 'Cashew Splits',
        rating: 4,
        price: '₹425.00',
        image: 'Images/ProductsImages/pepper cashew..png',
        unitsSold: 45,
    },
    {
        id: 3,
        category: 'Bangles',
        name: 'Roasted Cashew',
        rating: 4,
        price: '₹425.00',
        image: 'Images/ProductsImages/Purely Delight (1).png',
        unitsSold: 43,
    },
    {
        id: 4,
        category: 'Bangles',
        name: 'Roasted Cashew',
        rating: 3,
        price: '₹800',
        image: 'Images/ProductsImages/Purely Delight (2).png',
        unitsSold: 25,
    },
    {
        id: 5,
        category: 'Bangles',
        name: 'Roasted Cashew',
        rating: 4,
        price: '₹425.00',
        image: 'Images/ProductsImages/Purely Delight (3).png',
        unitsSold: 43,
    },
    // {
    //     id: 6,
    //     category: 'Bangles',
    //     name: 'Roasted Cashew',
    //     rating: 4,
    //     price: '₹425.00',
    //     image: 'Images/ProductsImages/Purely Delight (4).png',
    //     unitsSold: 43,
    // },
        // {
        //     id: 7,
        //     category: 'Bangles',
        //     name: 'Roasted Cashew',
        //     rating: 4,
        //     price: '₹425.00',
        //     image: 'Images/ProductsImages/Purely Delight (5).png',
        //     unitsSold: 43,
        // },
    {
        id: 8,
        category: 'Bangles',
        name: 'Roasted Cashew',
        rating: 4,
        price: '₹425.00',
        image: 'Images/ProductsImages/Purely Delight (6).png',
        unitsSold: 43,
    },
    {
        id: 9,
        category: 'Bangles',
        name: 'Roasted Cashew',
        rating: 4,
        price: '₹425.00',
        image: 'Images/ProductsImages/Purely Delight (7).png',
        unitsSold: 43,
    },
    {
        id: 10,
        category: 'Bangles',
        name: 'Roasted Cashew',
        rating: 4,
        price: '₹425.00',
        image: 'Images/ProductsImages/sunflower seeds.png',
        unitsSold: 43,
    },
    {
        id: 11,
        category: 'Bangles',
        name: 'Roasted Cashew',
        rating: 4,
        price: '₹425.00',
        image: 'Images/ProductsImages/wallnut.png',
        unitsSold: 43,
    },
    {
        id: 12,
        category: 'Bangles',
        name: 'Roasted Cashew',
        rating: 4,
        price: '₹425.00',
        image: 'Images/ProductsImages/watermelon seeds.png',
        unitsSold: 43,
    },
];

export const footerProducts = [
    {
        id: 1,
        category: 'Bangles',
        name: 'Cashew',
        rating: 5,
        price: '₹365.00',
        image: 'Images/ProductsImages/cashew-2.png',
        unitsSold: '50',
    },
    {
        id: 2,
        category: 'Bangles',
        name: 'Cashew Splits',
        rating: 4,
        price: '₹425.00',
        image: 'Images/ProductsImages/pepper cashew..png',
        unitsSold: 45,
    },
    {
        id: 3,
        category: 'Bangles',
        name: 'Roasted Cashew',
        rating: 4,
        price: '₹425.00',
        image: 'Images/ProductsImages/Purely Delight (1).png',
        unitsSold: 43,
    },
    {
        id: 4,
        category: 'Bangles',
        name: 'Roasted Cashew',
        rating: 3,
        price: '₹800',
        image: 'Images/ProductsImages/Purely Delight (2).png',
        unitsSold: 25,
    },
    {
        id: 5,
        category: 'Bangles',
        name: 'Roasted Cashew',
        rating: 4,
        price: '₹425.00',
        image: 'Images/ProductsImages/Purely Delight (3).png',
        unitsSold: 43,
    },
    {
        id: 8,
        category: 'Bangles',
        name: 'Roasted Cashew',
        rating: 4,
        price: '₹425.00',
        image: 'Images/ProductsImages/Purely Delight (6).png',
        unitsSold: 43,
    },
    {
        id: 9,
        category: 'Bangles',
        name: 'Roasted Cashew',
        rating: 4,
        price: '₹425.00',
        image: 'Images/ProductsImages/Purely Delight (7).png',
        unitsSold: 43,
    },
    {
        id: 10,
        category: 'Bangles',
        name: 'Roasted Cashew',
        rating: 4,
        price: '₹425.00',
        image: 'Images/ProductsImages/sunflower seeds.png',
        unitsSold: 43,
    },
    {
        id: 11,
        category: 'Bangles',
        name: 'Roasted Cashew',
        rating: 4,
        price: '₹425.00',
        image: 'Images/ProductsImages/wallnut.png',
        unitsSold: 43,
    },
    {
        id: 12,
        category: 'Bangles',
        name: 'Roasted Cashew',
        rating: 4,
        price: '₹425.00',
        image: 'Images/ProductsImages/watermelon seeds.png',
        unitsSold: 43,
    },
];